apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb
subjects:
- kind: ServiceAccount
  name: default
  namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: metallb-system
  apiGroup: rbac.authorization.k8s.io